/* SSD1306 SH1106 OLED
 * File: me_ssd1306.c
 * Started: Sun 17 Nov 2019 01:17:48 PM MSK
 * Author: Max Amzarakov (maxam18 _at_ gmail _._ com)
 * Copyright (c) 2019 ..."
 */

#include <string.h>

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"

#include "sdkconfig.h" // generated by "make menuconfig"


#include "me_ssd1306.h"
#include "me_ssd1306_defs.h"
#include "font8x8_basic.h"

esp_err_t me_ssd1306_init(me_ssd1306_conf_t *c)
{
    uint8_t     req[] = {
                          ME_SSD1306_CMD_STREAM
                        , ME_SSD1306_CMD_DISPLAY_OFF
                        , ME_SSD1306_CMD_SET_MUX_RATIO
                        , 0x3F                                  // index 3
                        , ME_SSD1306_CMD_SET_DISPLAY_OFFSET, 0x00
                        , ME_SSD1306_REG_DATA_STREAM
                        , ME_SSD1306_CMD_SET_SEGMENT_REMAP_OFF  // index 7
                        , ME_SSD1306_CMD_SET_COM_SCAN_MODE
                        , ME_SSD1306_CMD_SET_DISPLAY_CLK_DIV, 0x80
                        , ME_SSD1306_CMD_SET_COM_PIN_MAP
                        , 0x12                                  // index 12
                        , ME_SSD1306_CMD_SET_CONTRAST, 0xFF
                        , ME_SSD1306_CMD_DISPLAY_RAM
                        , ME_SSD1306_CMD_SET_VCOMH_DESELCT, 0x40
                        , ME_SSD1306_CMD_SET_MEMORY_ADDR_MODE
                        , ME_SSD1306_CMD_SET_PAGE_ADDR_MODE, 0x00, 0x10
                        , ME_SSD1306_CMD_SET_CHARGE_PUMP, 0x14
                        , ME_SSD1306_CMD_SCROLL_OFF
                        , ME_SSD1306_CMD_DISPLAY_NORMAL
                        , ME_SSD1306_CMD_DISPLAY_ON
                    };

    if( c->height == ME_SSD1306_H32 )
    {
        req[3]   = 0x1F; 
        req[12]  = 0x02; 
        c->_rows = 4;
    } else 
        c->_rows = 8;

    if( c->flip == ME_SSD1306_FLIP )
        req[7] = ME_SSD1306_CMD_SET_SEGMENT_REMAP_ON;

    return me_i2c_write(c->port, c->addr, req, sizeof(req));
}

esp_err_t me_ssd1306_display_clear(me_ssd1306_conf_t *c)
{
    esp_err_t   err;
	uint8_t     req[3+128], i;

    bzero(req, sizeof(req));
    req[0] = ME_SSD1306_CMD_SINGLE;
    req[2] = ME_SSD1306_REG_DATA_STREAM;

	for( i = 0; i < 8; i++ )
    {
        req[1] = 0xB0 | i;
        err = me_i2c_write(c->port, c->addr, req, sizeof(req));
        if( err != ESP_OK )
            break;
	}

    return err;
}


esp_err_t me_ssd1306_contrast(me_ssd1306_conf_t *c, int val)
{
	uint8_t     req[] = {
                          ME_SSD1306_CMD_STREAM
                        , ME_SSD1306_CMD_SET_CONTRAST
                        , 0
                    };

    req[2] = val & 0xFF;

    return me_i2c_write(c->port, c->addr, req, sizeof(req));
}


esp_err_t me_ssd1306_onoff(me_ssd1306_conf_t *c, int val)
{
	uint8_t     req[1];

    req[0] = val ? 0xAF : 0xAE;

    return me_i2c_write(c->port, c->addr, req, sizeof(req));
}



static esp_err_t reset_row(me_ssd1306_conf_t *c, uint8_t row)
{
    uint8_t     req[] =  { ME_SSD1306_CMD_STREAM, 0x00, 0x10, 0xB0 };

    if( row > c->_rows )
        return ESP_ERR_INVALID_ARG;

    req[3] |= row; /* reset page */

    return me_i2c_write(c->port, c->addr, req, sizeof(req));
}


esp_err_t me_ssd1306_8x8_string(me_ssd1306_conf_t *c, char *str, int row)
{
    esp_err_t   err;
    uint8_t     req[9];
    char       *p;
    int         line = 128/8;

    if( c->flip )
        row = (c->_rows - row) - 1;

    err = reset_row(c, row);
    if( err != ESP_OK )
        return err;

    req[0] = ME_SSD1306_REG_DATA_STREAM;

	for (p = str; *p && line; p++, line--)
    {
        memcpy(req+1, font8x8_basic_tr[(uint8_t)*p], 8);

        err = me_i2c_write(c->port, c->addr, req, 9);
        if( err != ESP_OK )
            break;
	}

    return err;
}

esp_err_t me_ssd1306_8x8_text(me_ssd1306_conf_t *c, const char *text)
{
	esp_err_t       err;
    uint8_t         req[9], row = 0;
    int             line = 128/8;
    const char     *p;

    if( c->flip )
        row = (c->_rows - row) - 1;

    err = reset_row(c, row);
    if( err != ESP_OK )
        return err;

    req[0] = ME_SSD1306_REG_DATA_STREAM;
	for( p = text; *p; p++ )
    {
		if( *p == '\n' )
        {
            if( c->flip )
                row--;
            else
                row++;

            err = reset_row(c, ++row);
            if( err != ESP_OK )
                break;
            
            line = 128/8;
		} else if( line-- > 0)
        {
            memcpy(req+1, font8x8_basic_tr[(uint8_t)*p], 8);

            err = me_i2c_write(c->port, c->addr, req, 9);
            if( err != ESP_OK )
                break;
            
		}
	}

    return err;
}


esp_err_t me_ssd1306_scroll(me_ssd1306_conf_t *c, me_ssd1306_scroll_t dir)
{
	uint8_t     req[10], len;

    switch( dir )
    {
    case ME_SSD1306_SCROLL_LEFT :
        req[0] = ME_SSD1306_CMD_SCROLL_LEFT;
        req[1] = 0x00; 
        req[2] = 0x00; 
        req[3] = 0x07; 
        req[4] = 0x07; 
        req[5] = 0x00; 
        req[6] = 0xFF;
        req[6] = ME_SSD1306_CMD_SCROLL_ON;
        len = 8; 
        break;
    case ME_SSD1306_SCROLL_RIGHT :
        req[0] = ME_SSD1306_CMD_SCROLL_RIGHT;
        req[1] = 0x00; 
        req[2] = 0x00; 
        req[3] = 0x07; 
        req[4] = 0x07; 
        req[5] = 0x00; 
        req[6] = 0xFF;
        req[6] = ME_SSD1306_CMD_SCROLL_ON;
        len = 8;
        break;
    case ME_SSD1306_SCROLL_UP :
        req[0] = ME_SSD1306_CMD_SCROLL_CONT;
        req[1] = 0x00; 
        req[2] = 0x00; 
        req[3] = 0x07; 
        req[4] = 0x00; 
        req[5] = 0x3F; /* vertical offset */
        req[6] = ME_SSD1306_CMD_VERTICAL;
        req[7] = 0x00;
        req[8] = (c->height == ME_SSD1306_H64) ? 0x40 : 0x20;
        req[9] = ME_SSD1306_CMD_SCROLL_ON;
        len = 10;
        break;
    case ME_SSD1306_SCROLL_DOWN :
        req[0] = ME_SSD1306_CMD_SCROLL_CONT;
        req[1] = 0x00; 
        req[2] = 0x00; 
        req[3] = 0x07; 
        req[4] = 0x00; 
        req[5] = 0x01; /* vertical offset */
        req[6] = ME_SSD1306_CMD_VERTICAL;
        req[7] = 0x00;
        req[8] = (c->height == ME_SSD1306_H64) ? 0x40 : 0x20;
        req[9] = ME_SSD1306_CMD_SCROLL_ON;
        len = 10;
        break;
    case ME_SSD1306_SCROLL_OFF :
    default:
        req[0] = ME_SSD1306_CMD_SCROLL_OFF;
        len = 1;
        break;
    }

    return me_i2c_write(c->port, c->addr, req, len);	
}

